# Vexplore installer - generated by vexelray-installer. Do not edit by hand; regenerate it.
#
#   irm https://raw.githubusercontent.com/sibarum/vexplore/main/install.ps1 | iex
#
# Options (set as environment variables before running the line above):
#   INSTALL_VERSION=1.2.3    install a specific version instead of the latest
#   INSTALL_DIR=C:\some\dir  install somewhere other than the default
#   INSTALL_NO_SHORTCUTS=1   skip the desktop / Start menu shortcuts
#   INSTALL_NO_PATH=1        do not add anything to the user PATH
#   INSTALL_NO_ASSOCIATIONS=1  do not register file types
#   INSTALL_FORCE=1          reinstall even if this version is already installed
#
# The same options are accepted as arguments when the script is run from a file:
#   -Version 1.2.3  -Dir C:\some\dir  -NoShortcuts  -NoPath  -NoAssociations  -Force

$InstallerCfg = '{"id":"vexplore","name":"Vexplore","publisher":"sibarum","manifestUrl":"https://raw.githubusercontent.com/sibarum/vexplore/main/manifest.json","registryDir":"%LOCALAPPDATA%\\vexelray-installer\\installs"}' | ConvertFrom-Json

function ViStep([string]$m) { Write-Host "==> $m" -ForegroundColor Cyan }
function ViInfo([string]$m) { Write-Host "    $m" }
function ViExpand([string]$p) { [Environment]::ExpandEnvironmentVariables($p) }
function ViSha([string]$p) { (Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant() }

function ViRegistryDir {
    if ($env:INSTALL_REGISTRY_DIR) { return $env:INSTALL_REGISTRY_DIR }
    ViExpand $InstallerCfg.registryDir
}

function ViGet([string]$url) {
    $c = (Invoke-WebRequest -UseBasicParsing -Uri $url).Content
    if ($c -is [byte[]]) { $c = [Text.Encoding]::UTF8.GetString($c) }
    $c
}

function ViWriteText([string]$path, [string]$text) {
    [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding $false))
}

function ViEnsureDir([string]$dir) {
    if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
}

# ---- user PATH (HKCU\Environment) ------------------------------------------------------

function ViBroadcastEnv {
    try {
        if (-not ('ViWin.ViNative' -as [type])) {
            Add-Type -Namespace ViWin -Name ViNative -MemberDefinition '[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)] public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);'
        }
        $r = [UIntPtr]::Zero
        [ViWin.ViNative]::SendMessageTimeout([IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$r) | Out-Null
    } catch { }
}

function ViUserPathGet {
    $k = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment')
    try { $k.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames) } finally { $k.Close() }
}

function ViUserPathSet([string]$value) {
    $k = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
    try {
        $kind = [Microsoft.Win32.RegistryValueKind]::ExpandString
        if ($k.GetValueNames() -contains 'Path') { $kind = $k.GetValueKind('Path') }
        $k.SetValue('Path', $value, $kind)
    } finally { $k.Close() }
    ViBroadcastEnv
}

function ViPathNorm([string]$p) { (ViExpand $p).TrimEnd('\').ToLowerInvariant() }

# Returns $true when the directory was added (i.e. it was not on the user PATH already).
function ViPathAdd([string]$dir) {
    $cur = [string](ViUserPathGet)
    foreach ($p in ($cur -split ';')) { if ($p -and (ViPathNorm $p) -eq (ViPathNorm $dir)) { return $false } }
    if ($cur -and -not $cur.EndsWith(';')) { $cur += ';' }
    ViUserPathSet ($cur + $dir)
    $env:Path = "$env:Path;$dir"
    return $true
}

function ViPathRemove([string]$dir) {
    $parts = @((ViUserPathGet) -split ';')
    $keep = @($parts | Where-Object { -not $_ -or (ViPathNorm $_) -ne (ViPathNorm $dir) })
    if ($keep.Count -ne $parts.Count) { ViUserPathSet ($keep -join ';') }
}

# ---- file associations (HKCU\Software\Classes) ------------------------------------------

function ViNotifyAssoc {
    try {
        if (-not ('ViWin.ViShell' -as [type])) {
            Add-Type -Namespace ViWin -Name ViShell -MemberDefinition '[DllImport("shell32.dll")] public static extern void SHChangeNotify(int wEventId, uint uFlags, IntPtr dwItem1, IntPtr dwItem2);'
        }
        [ViWin.ViShell]::SHChangeNotify(0x08000000, 0, [IntPtr]::Zero, [IntPtr]::Zero)
    } catch { }
}

# Writes the ProgID and lists it under the extension's OpenWithProgids ("Open with"). It becomes the
# extension's default only when neither the user's nor the machine's classes name one already; the
# record keeps whether it did, so removal clears only what this install set.
function ViAssocAdd($fa, [string]$command, [string]$icon) {
    $classes = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Software\Classes')
    try {
        $pk = $classes.CreateSubKey($fa.progId)
        try {
            $pk.SetValue('', [string]$fa.description)
            if ($icon) { $ik = $pk.CreateSubKey('DefaultIcon'); $ik.SetValue('', "$icon,0"); $ik.Close() }
            else { $pk.DeleteSubKeyTree('DefaultIcon', $false) }
            $ck = $pk.CreateSubKey('shell\open\command'); $ck.SetValue('', $command); $ck.Close()
        } finally { $pk.Close() }
        $ek = $classes.CreateSubKey($fa.extension)
        try {
            $ow = $ek.CreateSubKey('OpenWithProgids'); $ow.SetValue($fa.progId, ''); $ow.Close()
            $cur = [string]$ek.GetValue('')
            $isDefault = $cur -eq $fa.progId
            if (-not $cur) {
                $taken = $false
                $mk = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("Software\Classes\$($fa.extension)")
                if ($mk) { try { $taken = [bool]$mk.GetValue('') } finally { $mk.Close() } }
                if (-not $taken) { $ek.SetValue('', $fa.progId); $isDefault = $true }
            }
            $ctype = $null
            if ($isDefault -and $fa.contentType) {
                $have = [string]$ek.GetValue('Content Type')
                if (-not $have) { $ek.SetValue('Content Type', [string]$fa.contentType) }
                if (-not $have -or $have -eq $fa.contentType) { $ctype = [string]$fa.contentType }
            }
        } finally { $ek.Close() }
    } finally { $classes.Close() }
    [ordered]@{ extension = $fa.extension; progId = $fa.progId; isDefault = $isDefault; contentType = $ctype }
}

# Undoes ViAssocAdd for one install-record entry; leaves anything another program put on the extension.
function ViAssocRemove($a) {
    $classes = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Software\Classes', $true)
    if (-not $classes) { return }
    try {
        $classes.DeleteSubKeyTree($a.progId, $false)
        $ek = $classes.OpenSubKey($a.extension, $true)
        if (-not $ek) { return }
        try {
            $ow = $ek.OpenSubKey('OpenWithProgids', $true)
            if ($ow) {
                try { $ow.DeleteValue($a.progId, $false); $owEmpty = $ow.ValueCount -eq 0 -and $ow.SubKeyCount -eq 0 } finally { $ow.Close() }
                if ($owEmpty) { $ek.DeleteSubKeyTree('OpenWithProgids', $false) }
            }
            if ([string]$ek.GetValue('') -eq $a.progId) { $ek.DeleteValue('', $false) }
            if ($a.contentType -and [string]$ek.GetValue('Content Type') -eq $a.contentType) { $ek.DeleteValue('Content Type', $false) }
            $extEmpty = $ek.ValueCount -eq 0 -and $ek.SubKeyCount -eq 0
        } finally { $ek.Close() }
        if ($extEmpty) { $classes.DeleteSubKeyTree($a.extension, $false) }
    } finally { $classes.Close() }
}

# ---- versions ---------------------------------------------------------------------------

function ViVerKey([string]$v) {
    $core = ($v -replace '^[vV]', '') -replace '[-+].*$', ''
    if ($core -notmatch '\.') { $core = "$core.0" }
    try { $ver = [version]$core } catch { $ver = [version]'0.0' }
    [pscustomobject]@{ Ver = $ver; Pre = [bool]($v -match '-') }
}

function ViCompare([string]$a, [string]$b) {
    $x = ViVerKey $a; $y = ViVerKey $b
    $c = $x.Ver.CompareTo($y.Ver)
    if ($c -ne 0) { return $c }
    if ($x.Pre -and -not $y.Pre) { return -1 }
    if (-not $x.Pre -and $y.Pre) { return 1 }
    return 0
}

# ---- java (only matters for uberjar binaries) ------------------------------------------

function ViFindJava([string]$exe) {
    $c = Get-Command $exe -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($c) { return $c.Source }
    if ($env:JAVA_HOME) {
        $p = Join-Path (Join-Path $env:JAVA_HOME 'bin') "$exe.exe"
        if (Test-Path -LiteralPath $p) { return $p }
    }
    return $null
}

function ViJavaMajor([string]$javaExe) {
    try {
        $o = (& cmd.exe /c "`"$javaExe`" -version 2>&1") -join ' '
        if ($o -match 'version "(\d+)(?:\.(\d+))?') {
            $m = [int]$Matches[1]
            if ($m -eq 1 -and $Matches[2]) { $m = [int]$Matches[2] }
            return $m
        }
    } catch { }
    return 0
}

# Authenticode check for a downloaded native executable, when the manifest says it is signed.
# With a pinned thumbprint a certificate Windows cannot chain to a trusted root (a self-signed one)
# is accepted if it is exactly that certificate; without one the signature must be trusted.
function ViCheckSignature([string]$path, $meta, [string]$label) {
    if (-not $meta) { return }
    $sig = Get-AuthenticodeSignature -LiteralPath $path
    $st = [string]$sig.Status
    if ($st -eq 'NotSigned') { throw "$label is not signed, but the manifest says it is signed by $($meta.subject). Nothing was installed." }
    if ($st -eq 'HashMismatch') { throw "$label was altered after it was signed. Nothing was installed." }
    $cert = $sig.SignerCertificate
    if (-not $cert) { throw "$label has no usable signature ($st). Nothing was installed." }
    if ($cert.Subject.IndexOf([string]$meta.subject, [StringComparison]::OrdinalIgnoreCase) -lt 0) {
        throw "$label is signed by $($cert.Subject), not $($meta.subject). Nothing was installed."
    }
    if ($meta.thumbprint) {
        if ($cert.Thumbprint -ne ([string]$meta.thumbprint).ToUpperInvariant()) {
            throw "$label is signed by a different certificate than the manifest pins ($($cert.Thumbprint)). Nothing was installed."
        }
        if ($st -ne 'Valid') { Write-Warning "$label is signed by the pinned certificate $($cert.Thumbprint), which this machine does not trust ($st)." }
    } elseif ($st -ne 'Valid') {
        throw "$label has a signature from $($cert.Subject) that is not trusted ($st). Nothing was installed."
    }
    ViInfo "$label signed by $($cert.Subject)"
}

# Unpacks a zip, refusing entries that would land outside $dest.
function ViExpandZip([string]$zip, [string]$dest) {
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    ViEnsureDir $dest
    $root = [IO.Path]::GetFullPath($dest).TrimEnd('\') + '\'
    $z = [IO.Compression.ZipFile]::OpenRead($zip)
    try {
        foreach ($e in $z.Entries) {
            $p = [IO.Path]::GetFullPath((Join-Path $dest $e.FullName))
            if (-not $p.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) { throw "Archive entry would leave the target folder: $($e.FullName)" }
            if ($e.FullName.EndsWith('/') -or $e.FullName.EndsWith('\')) { ViEnsureDir $p; continue }
            ViEnsureDir (Split-Path $p -Parent)
            [IO.Compression.ZipFileExtensions]::ExtractToFile($e, $p, $true)
        }
    } finally { $z.Dispose() }
}

function ViReadRecord([string]$id) {
    $p = Join-Path (ViRegistryDir) "$id.json"
    if (Test-Path -LiteralPath $p) { try { return (Get-Content -Raw -LiteralPath $p | ConvertFrom-Json) } catch { } }
    return $null
}

function ViQuoteArg([string]$a) { if ($a -match '\s') { "`"$a`"" } else { $a } }

function ViJvmArgs($b) {
    $o = @()
    foreach ($a in @($b.jvmArgs)) { if ($a) { $o += (ViQuoteArg $a) } }
    return ($o -join ' ')
}

# The .cmd that starts a jar. With a runtime it reads <registryDir>\<runtime>.home (one line: that
# install's folder) every time, so updating the runtime never leaves launchers pointing at a stale JVM.
function ViJarLauncher($b, [string]$jarName) {
    $jvm = ViJvmArgs $b
    if ($jvm) { $jvm = " $jvm" }
    if ($b.runtime) {
        $ptr = Join-Path (ViRegistryDir) "$($b.runtime).home"
        return "@echo off`r`nsetlocal`r`nset `"VI_RT=`"`r`nset /p VI_RT=<`"$ptr`"`r`nif not exist `"%VI_RT%\bin\java.exe`" (`r`n  echo %~n0: the runtime '$($b.runtime)' is not installed 1>&2`r`n  exit /b 1`r`n)`r`n`"%VI_RT%\bin\java.exe`"$jvm -jar `"%~dp0$jarName`" %*`r`n"
    }
    return "@echo off`r`njava$jvm -jar `"%~dp0$jarName`" %*`r`n"
}

# javaw.exe for a jar's windowed start (shortcuts, file associations): its runtime install's, or the one
# on PATH / JAVA_HOME. $null means start it through the .cmd launcher instead.
function ViJavaw($b) {
    if (-not $b.runtime) { return (ViFindJava 'javaw') }
    $rt = ViReadRecord $b.runtime
    if ($rt) {
        $cand = Join-Path $rt.installDir 'bin\javaw.exe'
        if (Test-Path -LiteralPath $cand) { return $cand }
    }
    return $null
}

function ViShortcut([string]$lnk, [string]$target, [string]$arguments, [string]$workDir, [string]$desc, [string]$icon) {
    ViEnsureDir (Split-Path $lnk -Parent)
    $s = (New-Object -ComObject WScript.Shell).CreateShortcut($lnk)
    $s.TargetPath = $target
    if ($arguments) { $s.Arguments = $arguments }
    if ($workDir) { $s.WorkingDirectory = $workDir }
    if ($desc) { $s.Description = $desc }
    if ($icon) { $s.IconLocation = "$icon,0" }
    $s.Save()
}

# ---- install ---------------------------------------------------------------------------

function ViInvokeInstall {
    param([string]$Version, [string]$Dir, [switch]$NoShortcuts, [switch]$NoPath, [switch]$NoAssociations, [switch]$Force)
    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'
    $id = $InstallerCfg.id
    $appName = $InstallerCfg.name

    if ($env:OS -ne 'Windows_NT') { throw "${appName}: this installer supports Windows only for now." }
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

    ViStep "Fetching install manifest"
    $manifest = (ViGet $InstallerCfg.manifestUrl) | ConvertFrom-Json
    if ($manifest.id -ne $id) { throw "Manifest is for '$($manifest.id)', expected '$id'." }
    $want = if ($Version) { $Version -replace '^[vV]', '' } else { $manifest.latest }
    $entry = @($manifest.versions) | Where-Object { $_.version -eq $want } | Select-Object -First 1
    if (-not $entry) {
        $avail = (@($manifest.versions) | ForEach-Object { $_.version }) -join ', '
        throw "Version '$want' is not in the manifest. Available: $avail"
    }
    $plat = $entry.platforms.windows
    if (-not $plat) { throw "$appName $want has no Windows build." }

    foreach ($rq in @($plat.requires.installs)) {
        if (-not $rq.id) { continue }
        $dep = ViReadRecord $rq.id
        if (-not $dep) { throw "$appName needs '$($rq.id)' to be installed first. Install it, then run this again." }
        if ($rq.min -and (ViCompare $dep.version $rq.min) -lt 0) {
            throw "$appName needs $($rq.id) $($rq.min) or newer, but $($dep.version) is installed. Update it first."
        }
    }

    $regDir = ViRegistryDir
    $recPath = Join-Path $regDir "$id.json"
    $old = $null
    if (Test-Path -LiteralPath $recPath) {
        try { $old = Get-Content -Raw -LiteralPath $recPath | ConvertFrom-Json } catch { }
    }
    if ($Dir) { $installDir = (ViExpand $Dir).TrimEnd('\') }
    elseif ($old) { $installDir = $old.installDir }
    else { $installDir = (ViExpand $plat.installDir).TrimEnd('\') }

    if ($old -and $old.version -eq $entry.version -and $old.installDir -eq $installDir -and -not $Force) {
        Write-Host "$appName $($entry.version) is already installed in $installDir. Set INSTALL_FORCE=1 to reinstall."
        return $true
    }

    $bins = @($plat.binaries)
    $jars = @($bins | Where-Object { $_.kind -eq 'jar' -and -not $_.runtime })
    if ($jars.Count -gt 0) {
        $java = ViFindJava 'java'
        $need = [int]$plat.requires.java
        if (-not $java) {
            Write-Warning "Java was not found. $appName needs a Java runtime$(if ($need) { " (version $need or newer)" }) on PATH or JAVA_HOME to start."
        } elseif ($need -gt 0) {
            $major = ViJavaMajor $java
            if ($major -gt 0 -and $major -lt $need) { Write-Warning "Java $major found at $java, but $appName needs Java $need or newer." }
        }
    }

    $tmp = Join-Path ([IO.Path]::GetTempPath()) ("install-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $tmp | Out-Null
    try {
        # 1. download + verify everything before touching the install directory
        ViStep "Downloading $appName $($entry.version)"
        $staged = @()
        foreach ($b in $bins) {
            $ic = $null
            if ($b.icon) {
                $itarget = ViExpand $b.icon.installPath.Replace('{installDir}', $installDir)
                $itemp = $null
                if (-not ((Test-Path -LiteralPath $itarget) -and ((ViSha $itarget) -eq $b.icon.sha256))) {
                    ViInfo "$($b.icon.file)"
                    $itemp = Join-Path $tmp $b.icon.file
                    Invoke-WebRequest -UseBasicParsing -Uri $b.icon.url -OutFile $itemp
                    if ((ViSha $itemp) -ne $b.icon.sha256) { throw "Checksum mismatch for $($b.icon.file) downloaded from $($b.icon.url). Nothing was installed." }
                }
                $ic = [pscustomobject]@{ Target = $itarget; Temp = $itemp; Meta = $b.icon }
            }
            if ($b.kind -eq 'archive') {
                $adir = ViExpand $b.installPath.Replace('{installDir}', $installDir)
                $prev = $null
                if ($old) { $prev = @($old.archives) | Where-Object { $_.name -eq $b.name -and $_.sha256 -eq $b.sha256 -and $_.dir -eq $adir } | Select-Object -First 1 }
                $intact = [bool]$prev
                if ($intact) {
                    foreach ($f in @($old.files)) {
                        if ($f.kind -eq 'archive-file' -and $f.name -eq $b.name -and -not (Test-Path -LiteralPath $f.path)) { $intact = $false; break }
                    }
                }
                if ($intact) {
                    ViInfo "$($b.file) is already current"
                    $staged += [pscustomobject]@{ Bin = $b; Target = $adir; Temp = $null; Extracted = $null; Icon = $null }
                    continue
                }
                ViInfo ("{0} ({1:N1} MB)" -f $b.file, ($b.size / 1MB))
                $dl = Join-Path $tmp $b.file
                Invoke-WebRequest -UseBasicParsing -Uri $b.url -OutFile $dl
                if ((ViSha $dl) -ne $b.sha256) { throw "Checksum mismatch for $($b.file) downloaded from $($b.url). Nothing was installed." }
                ViInfo "Unpacking $($b.file)"
                $xdir = Join-Path $tmp ("x-" + $b.name)
                ViExpandZip $dl $xdir
                Remove-Item -Force -LiteralPath $dl
                $staged += [pscustomobject]@{ Bin = $b; Target = $adir; Temp = $null; Extracted = $xdir; Icon = $null }
                continue
            }
            $target = ViExpand $b.installPath.Replace('{installDir}', $installDir)
            if ((Test-Path -LiteralPath $target) -and ((ViSha $target) -eq $b.sha256)) {
                ViInfo "$($b.file) is already current"
                $staged += [pscustomobject]@{ Bin = $b; Target = $target; Temp = $null; Icon = $ic }
                continue
            }
            ViInfo ("{0} ({1:N1} MB)" -f $b.file, ($b.size / 1MB))
            $dl = Join-Path $tmp $b.file
            Invoke-WebRequest -UseBasicParsing -Uri $b.url -OutFile $dl
            if ((ViSha $dl) -ne $b.sha256) { throw "Checksum mismatch for $($b.file) downloaded from $($b.url). Nothing was installed." }
            ViCheckSignature $dl $b.signature $b.file
            $staged += [pscustomobject]@{ Bin = $b; Target = $target; Temp = $dl; Icon = $ic }
        }
        $tools = @()
        foreach ($tn in 'uninstall.ps1', 'update.ps1') {
            $t = $manifest.tools.$tn
            if (-not $t) { continue }
            $dl = Join-Path $tmp $tn
            Invoke-WebRequest -UseBasicParsing -Uri $t.url -OutFile $dl
            if ((ViSha $dl) -ne $t.sha256) { throw "Checksum mismatch for $tn downloaded from $($t.url). Nothing was installed." }
            $tools += [pscustomobject]@{ Name = $tn; Temp = $dl; Sha = $t.sha256 }
        }

        # 2. place files
        ViStep "Installing to $installDir"
        ViEnsureDir $installDir
        $files = @()
        $archives = @()
        foreach ($s in $staged) {
            if ($s.Bin.kind -eq 'archive') {
                ViEnsureDir $s.Target
                if ($s.Extracted) {
                    $xroot = $s.Extracted.TrimEnd('\')
                    foreach ($f in @(Get-ChildItem -LiteralPath $xroot -Recurse -File -Force)) {
                        $dest = Join-Path $s.Target $f.FullName.Substring($xroot.Length).TrimStart('\')
                        ViEnsureDir (Split-Path $dest -Parent)
                        try { Move-Item -Force -LiteralPath $f.FullName -Destination $dest }
                        catch { throw "Could not write ${dest}: $($_.Exception.Message) Close $appName if it is running and try again." }
                        $files += [ordered]@{ path = $dest; kind = 'archive-file'; name = $s.Bin.name; version = $s.Bin.version; sha256 = $null }
                    }
                } else {
                    foreach ($f in @($old.files)) { if ($f.kind -eq 'archive-file' -and $f.name -eq $s.Bin.name) { $files += $f } }
                }
                $archives += [ordered]@{ name = $s.Bin.name; version = $s.Bin.version; sha256 = $s.Bin.sha256; dir = $s.Target }
                continue
            }
            ViEnsureDir (Split-Path $s.Target -Parent)
            if ($s.Temp) {
                try { Move-Item -Force -LiteralPath $s.Temp -Destination $s.Target }
                catch { throw "Could not write $($s.Target): $($_.Exception.Message) Close $appName if it is running and try again." }
            }
            try { Unblock-File -LiteralPath $s.Target } catch { }
            $files += [ordered]@{ path = $s.Target; kind = 'binary'; name = $s.Bin.name; version = $s.Bin.version; sha256 = $s.Bin.sha256 }
            if ($s.Icon) {
                ViEnsureDir (Split-Path $s.Icon.Target -Parent)
                if ($s.Icon.Temp) { Move-Item -Force -LiteralPath $s.Icon.Temp -Destination $s.Icon.Target }
                $files += [ordered]@{ path = $s.Icon.Target; kind = 'icon'; name = $s.Bin.name; version = $s.Bin.version; sha256 = $s.Icon.Meta.sha256 }
            }
            if ($s.Bin.kind -eq 'jar') {
                $launcher = ViExpand $s.Bin.launcher.Replace('{installDir}', $installDir)
                ViWriteText $launcher (ViJarLauncher $s.Bin (Split-Path $s.Target -Leaf))
                $files += [ordered]@{ path = $launcher; kind = 'launcher'; name = $s.Bin.name; version = $s.Bin.version; sha256 = (ViSha $launcher) }
            }
        }
        foreach ($t in $tools) {
            $dest = Join-Path $installDir $t.Name
            try { Move-Item -Force -LiteralPath $t.Temp -Destination $dest }
            catch { Write-Warning "Could not replace $($t.Name) (in use?); run the update again later." ; if (-not (Test-Path -LiteralPath $dest)) { throw } }
            $files += [ordered]@{ path = $dest; kind = 'tool'; name = $t.Name; version = $entry.version; sha256 = $t.Sha }
            $wrapper = Join-Path $installDir ($t.Name -replace '\.ps1$', '.cmd')
            $wtext = "@echo off`r`npowershell.exe -NoProfile -ExecutionPolicy Bypass -File `"%~dp0$($t.Name)`" %*`r`nexit /b %errorlevel%`r`n"
            ViWriteText $wrapper $wtext
            $files += [ordered]@{ path = $wrapper; kind = 'tool'; name = (Split-Path $wrapper -Leaf); version = $entry.version; sha256 = (ViSha $wrapper) }
        }

        # other installs' launchers read this to find this install (see ViJarLauncher)
        ViEnsureDir $regDir
        $pointer = Join-Path $regDir "$id.home"
        ViWriteText $pointer "$installDir`r`n"
        $files += [ordered]@{ path = $pointer; kind = 'pointer'; name = "$id.home"; version = $entry.version; sha256 = (ViSha $pointer) }

        # 3. shortcuts
        $shortcuts = @()
        $skipShortcuts = $NoShortcuts -or [bool]$env:INSTALL_NO_SHORTCUTS
        if (-not $skipShortcuts) {
            foreach ($s in $staged) {
                $sc = $s.Bin.shortcuts
                if (-not $sc) { continue }
                $label = if ($sc.label) { $sc.label } else { $s.Bin.name }
                $target = $s.Target; $sargs = ''
                if ($s.Bin.kind -eq 'jar') {
                    $javaw = if ($sc.gui) { ViJavaw $s.Bin } else { $null }
                    if ($javaw) {
                        $target = $javaw
                        $sargs = (@((ViJvmArgs $s.Bin), "-jar `"$($s.Target)`"") | Where-Object { $_ }) -join ' '
                    }
                    else { $target = ViExpand $s.Bin.launcher.Replace('{installDir}', $installDir) }
                }
                $icon = if ($s.Icon) { $s.Icon.Target } elseif ($s.Bin.kind -eq 'native') { $s.Target } else { $null }
                $places = @()
                if ($sc.desktop) { $places += [Environment]::GetFolderPath('Desktop') }
                if ($sc.startMenu) { $places += [Environment]::GetFolderPath('Programs') }
                foreach ($pl in $places) {
                    $lnk = Join-Path $pl "$label.lnk"
                    ViShortcut $lnk $target $sargs $installDir "$appName" $icon
                    $shortcuts += $lnk
                    ViInfo "Shortcut: $lnk"
                }
            }
        }

        # 4. file associations: the binary gets the file as its last argument
        $associations = @()
        $skipAssoc = $NoAssociations -or [bool]$env:INSTALL_NO_ASSOCIATIONS
        if (-not $skipAssoc) {
            foreach ($s in $staged) {
                if (-not $s.Bin.fileAssociations) { continue }
                $cmd = "`"$($s.Target)`" `"%1`""
                if ($s.Bin.kind -eq 'jar') {
                    $javaw = if (@($s.Bin.fileAssociations)[0].gui) { ViJavaw $s.Bin } else { $null }
                    if ($javaw) { $cmd = ((@("`"$javaw`"", (ViJvmArgs $s.Bin), "-jar `"$($s.Target)`" `"%1`"") | Where-Object { $_ }) -join ' ') }
                    else { $cmd = "`"$(ViExpand $s.Bin.launcher.Replace('{installDir}', $installDir))`" `"%1`"" }
                }
                $icon = if ($s.Icon) { $s.Icon.Target } elseif ($s.Bin.kind -eq 'native') { $s.Target } else { $null }
                foreach ($fa in @($s.Bin.fileAssociations)) {
                    try {
                        $a = ViAssocAdd $fa $cmd $icon
                        $associations += $a
                        ViInfo ("Opens {0} files{1}" -f $fa.extension, $(if ($a.isDefault) { ' (default)' } else { ' (listed under Open with)' }))
                    } catch { Write-Warning "Could not register $($fa.extension): $($_.Exception.Message)" }
                }
            }
        }

        # 5. PATH
        $pathEntries = @()
        $skipPath = $NoPath -or [bool]$env:INSTALL_NO_PATH
        if (-not $skipPath) {
            $wanted = @()
            foreach ($s in $staged) {
                if (-not $s.Bin.addToPath) { continue }
                $p = if ($s.Bin.kind -eq 'jar') { ViExpand $s.Bin.launcher.Replace('{installDir}', $installDir) } else { $s.Target }
                $d = Split-Path $p -Parent
                if ($wanted -notcontains $d) { $wanted += $d }
            }
            foreach ($d in $wanted) {
                $added = ViPathAdd $d
                if ($added -or ($old -and (@($old.pathEntries) -contains $d))) { $pathEntries += $d }
                if ($added) { ViInfo "Added to user PATH: $d" }
            }
        }

        # 6. clean up whatever the previous install had that this one does not
        if ($old) {
            $newPaths = New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
            foreach ($nf in $files) { [void]$newPaths.Add([string]$nf.path) }
            foreach ($f in @($old.files)) {
                if ($f.path -and (-not $newPaths.Contains([string]$f.path)) -and (Test-Path -LiteralPath $f.path)) {
                    Remove-Item -Force -LiteralPath $f.path -ErrorAction SilentlyContinue
                }
            }
            # an updated archive may have dropped folders; remove the ones left empty
            foreach ($a in $archives) {
                if (-not (Test-Path -LiteralPath $a.dir)) { continue }
                Get-ChildItem -LiteralPath $a.dir -Directory -Recurse -Force |
                    Sort-Object { $_.FullName.Length } -Descending |
                    Where-Object { -not (Get-ChildItem -LiteralPath $_.FullName -Force) } |
                    Remove-Item -Force -ErrorAction SilentlyContinue
            }
            foreach ($l in @($old.shortcuts)) {
                if ($l -and ($shortcuts -notcontains $l) -and (Test-Path -LiteralPath $l)) { Remove-Item -Force -LiteralPath $l -ErrorAction SilentlyContinue }
            }
            foreach ($d in @($old.pathEntries)) {
                if ($d -and ($pathEntries -notcontains $d)) { ViPathRemove $d }
            }
            $keptProgIds = @($associations | ForEach-Object { $_.progId })
            foreach ($a in @($old.fileAssociations)) {
                if ($a -and $a.progId -and ($keptProgIds -notcontains $a.progId)) {
                    try { ViAssocRemove $a } catch { Write-Warning "Could not unregister $($a.extension): $($_.Exception.Message)" }
                }
            }
        }
        if ($associations.Count -gt 0 -or @($old.fileAssociations | Where-Object { $_ }).Count -gt 0) { ViNotifyAssoc }

        # 7. install manifest + uninstall registration
        # `commands` is how other installed programs find and start these binaries without
        # relying on PATH: name -> absolute path to run (the .cmd launcher for a jar).
        $commands = [ordered]@{}
        foreach ($s in $staged) {
            if ($s.Bin.kind -eq 'archive') {
                if ($s.Bin.exposes) {
                    foreach ($cn in $s.Bin.exposes.PSObject.Properties) {
                        $commands[$cn.Name] = [ordered]@{ path = (Join-Path $s.Target $cn.Value); kind = 'native'; version = $s.Bin.version }
                    }
                }
                continue
            }
            $run = if ($s.Bin.kind -eq 'jar') { ViExpand $s.Bin.launcher.Replace('{installDir}', $installDir) } else { $s.Target }
            $commands[$s.Bin.name] = [ordered]@{ path = $run; kind = $s.Bin.kind; version = $s.Bin.version }
        }
        $now = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
        $uninstallKey = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\$id"
        $record = [ordered]@{
            schemaVersion = 1
            id            = $id
            name          = $appName
            publisher     = $InstallerCfg.publisher
            version       = $entry.version
            platform      = 'windows'
            installedAt   = $(if ($old -and $old.installedAt) { $old.installedAt } else { $now })
            updatedAt     = $now
            installDir    = $installDir
            manifestUrl   = $InstallerCfg.manifestUrl
            requires      = @(@($plat.requires.installs) | Where-Object { $_ } | ForEach-Object { $_.id })
            commands      = $commands
            archives      = $archives
            files         = $files
            shortcuts     = $shortcuts
            pathEntries   = $pathEntries
            fileAssociations = $associations
            registryKeys  = @($uninstallKey)
        }
        $json = $record | ConvertTo-Json -Depth 10
        ViEnsureDir $regDir
        ViWriteText $recPath $json
        ViWriteText (Join-Path $installDir 'install-manifest.json') $json

        New-Item -Path $uninstallKey -Force | Out-Null
        $uninstallCmd = Join-Path $installDir 'uninstall.cmd'
        $icon = ($files | Where-Object { $_.kind -eq 'icon' } | Select-Object -First 1)
        if (-not $icon) { $icon = ($files | Where-Object { $_.kind -eq 'binary' -and $_.path -like '*.exe' } | Select-Object -First 1) }
        $sizeKb = [int]((($files | Where-Object { Test-Path -LiteralPath $_.path } | ForEach-Object { (Get-Item -LiteralPath $_.path).Length } | Measure-Object -Sum).Sum) / 1KB)
        $props = @{
            DisplayName          = $appName
            DisplayVersion       = $entry.version
            Publisher            = $InstallerCfg.publisher
            InstallLocation      = $installDir
            UninstallString      = "`"$uninstallCmd`""
            QuietUninstallString = "`"$uninstallCmd`" -Yes"
            InstallDate          = (Get-Date).ToString('yyyyMMdd')
        }
        if ($icon) { $props.DisplayIcon = $icon.path }
        foreach ($k in $props.Keys) { New-ItemProperty -Path $uninstallKey -Name $k -Value $props[$k] -PropertyType String -Force | Out-Null }
        New-ItemProperty -Path $uninstallKey -Name NoModify -Value 1 -PropertyType DWord -Force | Out-Null
        New-ItemProperty -Path $uninstallKey -Name NoRepair -Value 1 -PropertyType DWord -Force | Out-Null
        New-ItemProperty -Path $uninstallKey -Name EstimatedSize -Value $sizeKb -PropertyType DWord -Force | Out-Null

        Write-Host ""
        Write-Host "$appName $($entry.version) installed." -ForegroundColor Green
        Write-Host "    Location:  $installDir"
        Write-Host "    Manifest:  $recPath"
        Write-Host "    Update:    $(Join-Path $installDir 'update.cmd')"
        Write-Host "    Uninstall: $uninstallCmd   (or Settings > Apps)"
        if ($pathEntries.Count -gt 0) { Write-Host "    Open a new terminal for PATH changes to take effect." }
        return $true
    } finally {
        Remove-Item -Recurse -Force -LiteralPath $tmp -ErrorAction SilentlyContinue
    }
}

$ViArgs = @{}
if ($env:INSTALL_VERSION) { $ViArgs.Version = $env:INSTALL_VERSION }
if ($env:INSTALL_DIR) { $ViArgs.Dir = $env:INSTALL_DIR }
if ($env:INSTALL_FORCE) { $ViArgs.Force = $true }
for ($ViI = 0; $ViI -lt $args.Count; $ViI++) {
    switch -Regex ($args[$ViI]) {
        '^-Version$' { $ViI++; $ViArgs.Version = $args[$ViI] }
        '^-Dir$' { $ViI++; $ViArgs.Dir = $args[$ViI] }
        '^-NoShortcuts$' { $ViArgs.NoShortcuts = $true }
        '^-NoPath$' { $ViArgs.NoPath = $true }
        '^-NoAssociations$' { $ViArgs.NoAssociations = $true }
        '^-Force$' { $ViArgs.Force = $true }
        default { Write-Warning "Ignoring unknown argument: $($args[$ViI])" }
    }
}
$ViOk = $false
try {
    $ViOk = [bool](ViInvokeInstall @ViArgs | Select-Object -Last 1)
} catch {
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
}
if (-not $ViOk -and $PSCommandPath) { exit 1 }
