# Vexplore uninstaller - generated by vexelray-installer. Do not edit by hand.
#
# Finds installations through the install manifests in the registry directory
# (%LOCALAPPDATA%\vexelray-installer\installs by default), one JSON file per install.
#
#   uninstall.cmd                remove Vexplore
#   uninstall.cmd -List          list every install this machine knows about
#   uninstall.cmd -Id <id>       remove a specific install
#   uninstall.cmd -All           remove every install in the registry
#   uninstall.cmd -Yes           do not ask for confirmation

$InstallerCfg = '{"id":"vexplore","name":"Vexplore","publisher":"sibarum","manifestUrl":"https://raw.githubusercontent.com/sibarum/vexplore/main/manifest.json","registryDir":"%LOCALAPPDATA%\\vexelray-installer\\installs"}' | ConvertFrom-Json

function ViExpand([string]$p) { [Environment]::ExpandEnvironmentVariables($p) }

function ViRegistryDir {
    if ($env:INSTALL_REGISTRY_DIR) { return $env:INSTALL_REGISTRY_DIR }
    ViExpand $InstallerCfg.registryDir
}

function ViBroadcastEnv {
    try {
        if (-not ('ViWin.ViNative' -as [type])) {
            Add-Type -Namespace ViWin -Name ViNative -MemberDefinition '[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)] public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);'
        }
        $r = [UIntPtr]::Zero
        [ViWin.ViNative]::SendMessageTimeout([IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$r) | Out-Null
    } catch { }
}

function ViUserPathGet {
    $k = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment')
    try { $k.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames) } finally { $k.Close() }
}

function ViUserPathSet([string]$value) {
    $k = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
    try {
        $kind = [Microsoft.Win32.RegistryValueKind]::ExpandString
        if ($k.GetValueNames() -contains 'Path') { $kind = $k.GetValueKind('Path') }
        $k.SetValue('Path', $value, $kind)
    } finally { $k.Close() }
    ViBroadcastEnv
}

function ViPathNorm([string]$p) { (ViExpand $p).TrimEnd('\').ToLowerInvariant() }

function ViPathRemove([string]$dir) {
    $parts = @((ViUserPathGet) -split ';')
    $keep = @($parts | Where-Object { -not $_ -or (ViPathNorm $_) -ne (ViPathNorm $dir) })
    if ($keep.Count -ne $parts.Count) { ViUserPathSet ($keep -join ';') }
}

function ViNotifyAssoc {
    try {
        if (-not ('ViWin.ViShell' -as [type])) {
            Add-Type -Namespace ViWin -Name ViShell -MemberDefinition '[DllImport("shell32.dll")] public static extern void SHChangeNotify(int wEventId, uint uFlags, IntPtr dwItem1, IntPtr dwItem2);'
        }
        [ViWin.ViShell]::SHChangeNotify(0x08000000, 0, [IntPtr]::Zero, [IntPtr]::Zero)
    } catch { }
}

# Undoes the installer's ViAssocAdd for one install-record entry; leaves anything another program put
# on the extension.
function ViAssocRemove($a) {
    $classes = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Software\Classes', $true)
    if (-not $classes) { return }
    try {
        $classes.DeleteSubKeyTree($a.progId, $false)
        $ek = $classes.OpenSubKey($a.extension, $true)
        if (-not $ek) { return }
        try {
            $ow = $ek.OpenSubKey('OpenWithProgids', $true)
            if ($ow) {
                try { $ow.DeleteValue($a.progId, $false); $owEmpty = $ow.ValueCount -eq 0 -and $ow.SubKeyCount -eq 0 } finally { $ow.Close() }
                if ($owEmpty) { $ek.DeleteSubKeyTree('OpenWithProgids', $false) }
            }
            if ([string]$ek.GetValue('') -eq $a.progId) { $ek.DeleteValue('', $false) }
            if ($a.contentType -and [string]$ek.GetValue('Content Type') -eq $a.contentType) { $ek.DeleteValue('Content Type', $false) }
            $extEmpty = $ek.ValueCount -eq 0 -and $ek.SubKeyCount -eq 0
        } finally { $ek.Close() }
        if ($extEmpty) { $classes.DeleteSubKeyTree($a.extension, $false) }
    } finally { $classes.Close() }
}

function ViReadRecords {
    $dir = ViRegistryDir
    $out = @()
    if (-not (Test-Path -LiteralPath $dir)) { return $out }
    foreach ($f in Get-ChildItem -LiteralPath $dir -Filter *.json -File) {
        try {
            $r = Get-Content -Raw -LiteralPath $f.FullName | ConvertFrom-Json
            $r | Add-Member -NotePropertyName recordPath -NotePropertyValue $f.FullName -Force
            if ($r.id -and $r.installDir) { $out += $r }
        } catch { Write-Warning "Skipping unreadable manifest $($f.FullName)" }
    }
    return $out
}

# Files that belong to the running uninstaller can't be deleted while it runs.
$ViSelf = @()
if ($PSCommandPath) {
    $ViSelf += $PSCommandPath
    $ViSelf += (Join-Path (Split-Path $PSCommandPath -Parent) 'uninstall.cmd')
}

function ViRemoveOne($rec) {
    Write-Host "==> Removing $($rec.name) $($rec.version) from $($rec.installDir)" -ForegroundColor Cyan
    $deferred = @()
    foreach ($f in @($rec.files)) {
        if (-not $f.path -or -not (Test-Path -LiteralPath $f.path)) { continue }
        if ($ViSelf -contains $f.path) { $deferred += $f.path; continue }
        try { Remove-Item -Force -LiteralPath $f.path } catch { Write-Warning "Could not delete $($f.path): $($_.Exception.Message)" }
    }
    foreach ($l in @($rec.shortcuts)) {
        if ($l -and (Test-Path -LiteralPath $l)) { Remove-Item -Force -LiteralPath $l -ErrorAction SilentlyContinue }
    }
    foreach ($d in @($rec.pathEntries)) { if ($d) { ViPathRemove $d } }
    $assocs = @($rec.fileAssociations | Where-Object { $_ -and $_.progId })
    foreach ($a in $assocs) {
        try { ViAssocRemove $a } catch { Write-Warning "Could not unregister $($a.extension): $($_.Exception.Message)" }
    }
    if ($assocs.Count -gt 0) { ViNotifyAssoc }
    foreach ($k in @($rec.registryKeys)) {
        if ($k -and (Test-Path -LiteralPath $k)) { Remove-Item -Recurse -Force -LiteralPath $k -ErrorAction SilentlyContinue }
    }
    $mf = Join-Path $rec.installDir 'install-manifest.json'
    if (Test-Path -LiteralPath $mf) { Remove-Item -Force -LiteralPath $mf -ErrorAction SilentlyContinue }
    if ($rec.recordPath -and (Test-Path -LiteralPath $rec.recordPath)) { Remove-Item -Force -LiteralPath $rec.recordPath }

    # prune empty directories, deepest first; anything the user added stays
    if (Test-Path -LiteralPath $rec.installDir) {
        Get-ChildItem -LiteralPath $rec.installDir -Directory -Recurse -Force |
            Sort-Object { $_.FullName.Length } -Descending |
            Where-Object { -not (Get-ChildItem -LiteralPath $_.FullName -Force) } |
            Remove-Item -Force -ErrorAction SilentlyContinue
        $left = @(Get-ChildItem -LiteralPath $rec.installDir -Force | Where-Object { $deferred -notcontains $_.FullName })
        if ($left.Count -eq 0) {
            if ($deferred.Count -eq 0) { Remove-Item -Force -LiteralPath $rec.installDir -ErrorAction SilentlyContinue }
        } else {
            Write-Host "    Left in place (not installed by us): $($rec.installDir)" -ForegroundColor Yellow
        }
    }
    if ($deferred.Count -gt 0) {
        $quoted = ($deferred | ForEach-Object { "`"$_`"" }) -join ' '
        $line = "ping -n 3 127.0.0.1 >nul & del /f /q $quoted & rd `"$($rec.installDir)`" 2>nul"
        Start-Process -FilePath cmd.exe -ArgumentList "/c $line" -WindowStyle Hidden
    }
    Write-Host "    Removed." -ForegroundColor Green
}

function ViInvokeUninstall {
    param([string]$Id, [switch]$All, [switch]$List, [switch]$Yes)
    $ErrorActionPreference = 'Stop'
    $records = @(ViReadRecords)

    # fall back to the manifest sitting next to this script if the registry entry is gone
    if ($records.Count -eq 0 -and $PSCommandPath) {
        $local = Join-Path (Split-Path $PSCommandPath -Parent) 'install-manifest.json'
        if (Test-Path -LiteralPath $local) {
            $r = Get-Content -Raw -LiteralPath $local | ConvertFrom-Json
            $r | Add-Member -NotePropertyName recordPath -NotePropertyValue $null -Force
            $records = @($r)
        }
    }

    if ($List) {
        if ($records.Count -eq 0) { Write-Host "No installs found in $(ViRegistryDir)." }
        foreach ($r in $records) { Write-Host ("{0,-24} {1,-12} {2}" -f $r.id, $r.version, $r.installDir) }
        return $true
    }
    if ($records.Count -eq 0) { Write-Host "Nothing to uninstall: no install manifests in $(ViRegistryDir)."; return $true }

    if ($All) { $chosen = $records }
    else {
        $wantId = if ($Id) { $Id } else { $InstallerCfg.id }
        $chosen = @($records | Where-Object { $_.id -eq $wantId })
        if ($chosen.Count -eq 0) {
            Write-Host "'$wantId' is not installed. Installs on this machine:"
            foreach ($r in $records) { Write-Host ("  {0,-24} {1,-12} {2}" -f $r.id, $r.version, $r.installDir) }
            Write-Host "Use -Id <id> or -All."
            return $false
        }
    }

    $chosenIds = @($chosen | ForEach-Object { $_.id })
    foreach ($r in $chosen) {
        foreach ($u in @($records | Where-Object { ($chosenIds -notcontains $_.id) -and (@($_.requires) -contains $r.id) })) {
            Write-Warning "$($u.name) still needs $($r.name) and will not start without it."
        }
    }

    if (-not $Yes) {
        foreach ($r in $chosen) { Write-Host "Will remove $($r.name) $($r.version) ($($r.installDir))" }
        $a = Read-Host "Continue? [y/N]"
        if ($a -notmatch '^[yY]') { Write-Host "Cancelled."; return $false }
    }
    foreach ($r in $chosen) { ViRemoveOne $r }

    $regDir = ViRegistryDir
    if ((Test-Path -LiteralPath $regDir) -and -not (Get-ChildItem -LiteralPath $regDir -Force)) {
        Remove-Item -Force -LiteralPath $regDir -ErrorAction SilentlyContinue
        $parent = Split-Path $regDir -Parent
        if ((Test-Path -LiteralPath $parent) -and -not (Get-ChildItem -LiteralPath $parent -Force)) {
            Remove-Item -Force -LiteralPath $parent -ErrorAction SilentlyContinue
        }
    }
    return $true
}

$ViArgs = @{}
for ($ViI = 0; $ViI -lt $args.Count; $ViI++) {
    switch -Regex ($args[$ViI]) {
        '^-Id$' { $ViI++; $ViArgs.Id = $args[$ViI] }
        '^-All$' { $ViArgs.All = $true }
        '^-List$' { $ViArgs.List = $true }
        '^-Yes$' { $ViArgs.Yes = $true }
        default { Write-Warning "Ignoring unknown argument: $($args[$ViI])" }
    }
}
$ViOk = $false
try {
    $ViOk = [bool](ViInvokeUninstall @ViArgs | Select-Object -Last 1)
} catch {
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
}
if (-not $ViOk) { exit 1 }
