# Vexplore updater - generated by vexelray-installer. Do not edit by hand.
#
#   update.cmd          check for a newer version and install it (asks first)
#   update.cmd -Check   only report what is available
#   update.cmd -Yes     do not ask for confirmation

$InstallerCfg = '{"id":"vexplore","name":"Vexplore","publisher":"sibarum","manifestUrl":"https://raw.githubusercontent.com/sibarum/vexplore/main/manifest.json","registryDir":"%LOCALAPPDATA%\\vexelray-installer\\installs"}' | ConvertFrom-Json

function ViExpand([string]$p) { [Environment]::ExpandEnvironmentVariables($p) }
function ViSha([string]$p) { (Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant() }

function ViRegistryDir {
    if ($env:INSTALL_REGISTRY_DIR) { return $env:INSTALL_REGISTRY_DIR }
    ViExpand $InstallerCfg.registryDir
}

function ViGet([string]$url) {
    $c = (Invoke-WebRequest -UseBasicParsing -Uri $url).Content
    if ($c -is [byte[]]) { $c = [Text.Encoding]::UTF8.GetString($c) }
    $c
}

function ViVerKey([string]$v) {
    $core = ($v -replace '^[vV]', '') -replace '[-+].*$', ''
    if ($core -notmatch '\.') { $core = "$core.0" }
    try { $ver = [version]$core } catch { $ver = [version]'0.0' }
    [pscustomobject]@{ Ver = $ver; Pre = [bool]($v -match '-') }
}

function ViCompare([string]$a, [string]$b) {
    $x = ViVerKey $a; $y = ViVerKey $b
    $c = $x.Ver.CompareTo($y.Ver)
    if ($c -ne 0) { return $c }
    if ($x.Pre -and -not $y.Pre) { return -1 }
    if (-not $x.Pre -and $y.Pre) { return 1 }
    return 0
}

function ViInvokeUpdate {
    param([switch]$Check, [switch]$Yes)
    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'
    $id = $InstallerCfg.id
    $appName = $InstallerCfg.name
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

    $recPath = Join-Path (ViRegistryDir) "$id.json"
    if (-not (Test-Path -LiteralPath $recPath)) {
        throw "$appName is not installed (no manifest at $recPath). Run the install command from the README."
    }
    $rec = Get-Content -Raw -LiteralPath $recPath | ConvertFrom-Json

    Write-Host "==> Checking $($InstallerCfg.manifestUrl)" -ForegroundColor Cyan
    $manifest = (ViGet $InstallerCfg.manifestUrl) | ConvertFrom-Json
    $latest = @($manifest.versions) | Where-Object { $_.version -eq $manifest.latest } | Select-Object -First 1
    $plat = $latest.platforms.windows
    if (-not $plat) { throw "$appName $($manifest.latest) has no Windows build." }

    $changes = @()
    foreach ($b in @($plat.binaries)) {
        $have = if ($b.kind -eq 'archive') { @($rec.archives) | Where-Object { $_.name -eq $b.name } | Select-Object -First 1 }
                else { @($rec.files) | Where-Object { $_.kind -eq 'binary' -and $_.name -eq $b.name } | Select-Object -First 1 }
        if (-not $have) { $changes += "{0}: new (-> {1})" -f $b.name, $b.version; continue }
        $c = ViCompare $b.version $have.version
        if ($c -gt 0) { $changes += "{0}: {1} -> {2}" -f $b.name, $have.version, $b.version }
        elseif ($c -eq 0 -and $have.sha256 -ne $b.sha256) { $changes += "{0}: {1} was republished" -f $b.name, $b.version }
    }
    $newer = (ViCompare $manifest.latest $rec.version) -gt 0
    if (-not $newer -and $changes.Count -eq 0) {
        Write-Host "$appName $($rec.version) is up to date." -ForegroundColor Green
        return $true
    }

    Write-Host "Update available: $appName $($rec.version) -> $($manifest.latest)"
    foreach ($c in $changes) { Write-Host "    $c" }
    if ($latest.notes) { Write-Host "    Notes: $($latest.notes)" }
    if ($Check) { return $true }

    if (-not $Yes) {
        $a = Read-Host "Install it now? [y/N]"
        if ($a -notmatch '^[yY]') { Write-Host "Cancelled."; return $true }
    }

    $t = $manifest.tools.'install.ps1'
    $tmp = Join-Path ([IO.Path]::GetTempPath()) ("update-" + [guid]::NewGuid().ToString('N') + '.ps1')
    try {
        Invoke-WebRequest -UseBasicParsing -Uri $t.url -OutFile $tmp
        if ((ViSha $tmp) -ne $t.sha256) { throw "Checksum mismatch for install.ps1 downloaded from $($t.url). Update aborted." }
        $childArgs = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $tmp, '-Version', $manifest.latest, '-Dir', $rec.installDir, '-Force')
        & powershell.exe @childArgs | Out-Host
        if ($LASTEXITCODE -ne 0) { throw "The installer exited with code $LASTEXITCODE." }
    } finally {
        Remove-Item -Force -LiteralPath $tmp -ErrorAction SilentlyContinue
    }
    return $true
}

$ViArgs = @{}
foreach ($ViA in $args) {
    switch -Regex ($ViA) {
        '^-Check$' { $ViArgs.Check = $true }
        '^-Yes$' { $ViArgs.Yes = $true }
        default { Write-Warning "Ignoring unknown argument: $ViA" }
    }
}
$ViOk = $false
try {
    $ViOk = [bool](ViInvokeUpdate @ViArgs | Select-Object -Last 1)
} catch {
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
}
if (-not $ViOk) { exit 1 }
