# Vex, Vexplore and Pix installer - generated by vexelray-installer. Do not edit by hand; regenerate it.
#
#   irm https://raw.githubusercontent.com/sibarum/vexplore/main/suite/install.ps1 | iex
#
# Installs every application in the suite, each as an install of its own: its own folder, its own
# entry in Settings > Apps, its own updater and uninstaller. This script installs nothing itself. For
# each application it fetches the published install manifest, downloads that application's own
# install.ps1, checks it against the SHA-256 the manifest records, and runs it.
#
# Options (set as environment variables before running the line above):
#   INSTALL_ONLY=a,b           install only these applications (vexplore, text-editor, pix)
#   INSTALL_NO_SHORTCUTS=1     passed on to every application's installer
#   INSTALL_NO_PATH=1          "
#   INSTALL_NO_ASSOCIATIONS=1  "
#   INSTALL_FORCE=1            "
# INSTALL_VERSION and INSTALL_DIR name one application's version and folder, so they are not passed
# on: run that application's own installer to use them.

$SuiteCfg = '{"name":"Vex, Vexplore and Pix","members":[{"id":"vexplore","name":"Vexplore","manifestUrl":"https://raw.githubusercontent.com/sibarum/vexplore/main/manifest.json","registryDir":"%LOCALAPPDATA%\\vexelray-installer\\installs"},{"id":"text-editor","name":"Vex","manifestUrl":"https://raw.githubusercontent.com/sibarum/text-editor-vexel-demo/main/manifest.json","registryDir":"%LOCALAPPDATA%\\vexelray-installer\\installs"},{"id":"pix","name":"Pix","manifestUrl":"https://raw.githubusercontent.com/sibarum/Pix/main/manifest.json","registryDir":"%LOCALAPPDATA%\\vexelray-installer\\installs"}]}' | ConvertFrom-Json

function SuiteSha([string]$p) { (Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant() }

function SuiteRegistryDir($m) {
    if ($env:INSTALL_REGISTRY_DIR) { return $env:INSTALL_REGISTRY_DIR }
    [Environment]::ExpandEnvironmentVariables($m.registryDir)
}

function SuiteRecordVersion($m) {
    $p = Join-Path (SuiteRegistryDir $m) "$($m.id).json"
    if (-not (Test-Path -LiteralPath $p)) { return $null }
    try { (Get-Content -Raw -LiteralPath $p | ConvertFrom-Json).version } catch { $null }
}

function SuiteStatusCode($err) {
    $r = $err.Exception.Response
    if ($r -and $r.StatusCode) { return [int]$r.StatusCode }
    return 0
}

# Returns one of: installed, unpublished, failed.
function SuiteInstallOne($m, [string]$tmp) {
    Write-Host ""
    Write-Host "==> $($m.name)" -ForegroundColor Cyan
    try {
        $mf = "$tmp\$($m.id).manifest.json"
        try {
            Invoke-WebRequest -UseBasicParsing -Uri $m.manifestUrl -OutFile $mf
        } catch {
            if ((SuiteStatusCode $_) -eq 404) {
                Write-Host "    $($m.name) has not been published yet; skipped." -ForegroundColor Yellow
                return 'unpublished'
            }
            throw
        }
        $manifest = Get-Content -Raw -LiteralPath $mf | ConvertFrom-Json
        if ($manifest.id -ne $m.id) { throw "the manifest at $($m.manifestUrl) is for '$($manifest.id)', not '$($m.id)'" }
        $tool = $manifest.tools.'install.ps1'
        if (-not $tool -or -not $tool.url -or -not $tool.sha256) { throw "the manifest names no install.ps1" }
        $script = "$tmp\$($m.id).install.ps1"
        Invoke-WebRequest -UseBasicParsing -Uri $tool.url -OutFile $script
        if ((SuiteSha $script) -ne $tool.sha256) {
            throw "its install.ps1 does not match the SHA-256 in its manifest; it was not run"
        }
        # A script block of its own, so each installer's functions stay in its own scope. It reports its
        # own errors and does not throw, so whether it worked is read from the record it writes.
        $null = & ([scriptblock]::Create([IO.File]::ReadAllText($script)))
        if ((SuiteRecordVersion $m) -eq $manifest.latest) { return 'installed' }
        return 'failed'
    } catch {
        Write-Host "ERROR: $($m.name): $($_.Exception.Message)" -ForegroundColor Red
        return 'failed'
    }
}

function SuiteInstall {
    $ProgressPreference = 'SilentlyContinue'
    if ($env:OS -ne 'Windows_NT') { throw "$($SuiteCfg.name): this installer supports Windows only for now." }
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

    $members = @($SuiteCfg.members)
    if ($env:INSTALL_ONLY) {
        $want = @($env:INSTALL_ONLY -split '[,; ]+' | Where-Object { $_ } | ForEach-Object { $_.ToLowerInvariant() })
        $known = @($members | ForEach-Object { $_.id })
        $unknown = @($want | Where-Object { $known -notcontains $_ })
        if ($unknown.Count -gt 0) { throw "INSTALL_ONLY names $($unknown -join ', '), which the suite does not have. It has: $($known -join ', ')" }
        $members = @($members | Where-Object { $want -contains $_.id })
    }

    # Per-application options would apply to every application here, so they are set aside.
    $held = @{}
    foreach ($n in 'INSTALL_VERSION', 'INSTALL_DIR') {
        $v = [Environment]::GetEnvironmentVariable($n, 'Process')
        if ($v) {
            Write-Host "$n applies to one application and is ignored here; run that application's own installer to use it." -ForegroundColor Yellow
            $held[$n] = $v
            [Environment]::SetEnvironmentVariable($n, $null, 'Process')
        }
    }
    $tmp = Join-Path ([IO.Path]::GetTempPath()) ("vi-suite-" + [guid]::NewGuid().ToString('N').Substring(0, 8))
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    $results = @()
    try {
        Write-Host "Installing $($SuiteCfg.name): $(($members | ForEach-Object { $_.name }) -join ', ')"
        foreach ($m in $members) { $results += [pscustomobject]@{ Member = $m; Result = (SuiteInstallOne $m $tmp) } }
    } finally {
        foreach ($n in $held.Keys) { [Environment]::SetEnvironmentVariable($n, $held[$n], 'Process') }
        Remove-Item -Recurse -Force -LiteralPath $tmp -ErrorAction SilentlyContinue
    }

    Write-Host ""
    Write-Host "$($SuiteCfg.name):" -ForegroundColor Cyan
    foreach ($r in $results) {
        switch ($r.Result) {
            'installed' { Write-Host ("    {0,-20} {1}" -f $r.Member.name, (SuiteRecordVersion $r.Member)) -ForegroundColor Green }
            'unpublished' { Write-Host ("    {0,-20} not published yet" -f $r.Member.name) -ForegroundColor Yellow }
            default { Write-Host ("    {0,-20} FAILED (see above)" -f $r.Member.name) -ForegroundColor Red }
        }
    }
    return @($results | Where-Object { $_.Result -eq 'failed' }).Count -eq 0
}

$SuiteOk = $false
try {
    $SuiteOk = [bool](SuiteInstall | Select-Object -Last 1)
} catch {
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
}
if (-not $SuiteOk -and $PSCommandPath) { exit 1 }
